INSERT INTO CURRENCY VALUES (default, 13300, 'EU');
INSERT INTO CURRENCY VALUES (default, 11000, 'US');
INSERT INTO CURRENCY VALUES (default, 1, 'BY');

INSERT INTO ACCOUNT VALUES (default, 1, 2300);
INSERT INTO ACCOUNT VALUES (default, 2, 3500);

INSERT INTO PERSON VALUES (default, 1, 'Anton');
INSERT INTO PERSON VALUES (default, 2, 'Sergey');
